### ISSUE TITLE
users section not fixed please fix - see photos

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#142]
when clicking on the lower links as seen in photos color changes in the category section: contacts collections photos  etc...

![whenclicktheselinkscolorchanges](https://cloud.githubusercontent.com/assets/17736688/15739997/7c5a2a26-2878-11e6-9cc9-42260d7b4baf.JPG)
![wrong](https://cloud.githubusercontent.com/assets/17736688/15740005/81c6845a-2878-11e6-99d1-6a136bbcb161.JPG)

should not change colors for description - categories ??

**Comment by spirogg** [comment]
just installed master 1 hour ago fresh install still issue persists

**Comment by spirogg** [comment]
Thank you guys.

**Comment by spirogg** [comment]
this has not been fixed when you click on links above collections categories are white. when you click on links below collections categories are blue ??  please fix
![whenclicktheselinkscolorchanges](https://cloud.githubusercontent.com/assets/17736688/15854009/41f4aef8-2c6d-11e6-876f-5aba6318ba7f.JPG)
![wrong](https://cloud.githubusercontent.com/assets/17736688/15854017/46ddf320-2c6d-11e6-808f-71ec64e91d5f.JPG)

**Comment by spirogg** [comment]
@saqirzzq @sikanderzel please fix this one too

**Comment by sakydev** [comment]
Seems fixed at my side

**Comment by spirogg** [comment]
@saqirzzq i just uploaded all files again same issue click on manage photos then click on my account and see is it blue or white the categories

**Comment by spirogg** [comment]
@saqirzzq what file did he fix for this color change ??

**Comment by spirogg** [comment]
can you pone me to the file please where he made changes so the colors stay either white or blue as the categories and beneath them are the clickable links. cause on my side after uploading all your fixes tonight and updating all the files this morning it still is not fixed for me. every link above the category collections that you can click on seems the category ( none clickable) stay white or off white as shown in the photo, but if you click on add new collections - manage collections - manage photos - manage favorite photos - manage my album,  then the categories are changed to color blue ??

**Comment by spirogg** [comment]
ok for some reason whatever changes he made were not in the Master when i downloaded it earlier today ?? i just copied and pasted all his updates and now works like a charm

thank you @jamilrehman @saqirzzq for fixing
